apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: k1x-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: nginx:thistagdoesnotexist
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: k1x-apps
spec:
  selector:
    app: worker
  ports:
  - port: 80
    targetPort: 80
