apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: k1x-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nginx:1.25
        ports:
        - containerPort: 80
        env:
        - name: APP_ENV
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: environment
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: k1x-apps
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
